version: '3'
services:
  postgres:
    image: postgres:15-alpine3.18
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env

volumes:
  progresDB:
