@api = http://localhost:8000/api

### Obtener lista de cicloClase
GET {{api}}/cicloClase

### Crear un nuevo cicloClase
POST {{api}}/cicloClase
content-type: application/json

{
    "name": "23-02",
    "startDate": "2023-08-01T00:00:00.000Z",
    "endDate": "2023-12-01T00:00:00.000Z"
}

### Eliminar un cicloClase
DELETE {{api}}/cicloClase/3

### Actualizar parcialmente un cicloClase
PATCH {{api}}/cicloClase/1
content-type: application/json

{
    "name": "Nombre Ejemplo",
    "startDate": "2023-08-01T00:00:00Z",
    "endDate": "2023-12-01T00:00:00Z"
}